### ISSUE TITLE
Code Style

### ISSUE THREAD

**Issue by b1quint** [rcbrgs/tuna#1]
Shouldn't tuna coding style just follow the [PEP-8](https://www.python.org/dev/peps/pep-0008/), which is a standard for Python? There are IDE's that strongly encourages us to follow the PEP-8.

For example:
    \* [JetBrain's PyCharm](https://www.jetbrains.com/pycharm/) 
    \* [pep8](https://pypi.python.org/pypi/pep8) 
    \* [PEP-8 Online Checker](http://pep8online.com/)

**Comment by rcbrgs** [comment]
Hi Bruno! 
Thank you for tipping about pep 8, it is full of good recommendations. Although Tuna doesn't explicitly follows it, most of its recommendations are followed.
Also, I agree with the guiding principle that we should strive for homogeneity - but be free to break the rules when it makes code more readable.
I made some stylistic choices in Tuna which I simply "feel" make code more readable, but I think that depends on taste as well - and no one is obliged to agree with my taste in reading!

That being said, I guess we could say Tuna follows a "pep 8 derivative" where the few style rules listed on Tuna's documentation substitute the specific pep8 recommendations that they violate.

Regarding pull requests, you might want to know if I would accept code that is "strictly" pep8 compliant. That depends on the contribution length. If the request is just a bug fix or a small extension, I will ask it to be rewritten to follow all rules (including Tuna's). In the case of a larger contribution, I think it is ok to use a "strict" PEP8 if you feel more comfortable reading that.

**Comment by rcbrgs** [comment]
Tuna has been refactored to be PEP8 and PEP257 compliant. Thanks!
